const CONSTS = module.exports;

// Nível mínimo para o utilizador poder editar
CONSTS.NIVEL_MINIMO_ALTERAR = 4;
CONSTS.NIVEL_MINIMO_DISTRIBUIR_PEDIDOS = 4;
CONSTS.NIVEL_MINIMO_SUBSTITUIR_RESPONSAVEL = 4;
CONSTS.NIVEL_MINIMO_DOC = 3.5;

CONSTS.NIVEIS_DEVOLVER_PEDIDO_NOVO = [4, 6, 7];
CONSTS.NIVEIS_DISTRIBUIR_PEDIDO_NOVO = [4, 6, 7];
CONSTS.NIVEIS_ANALISAR_PEDIDO = [3.5, 4, 6, 7]; // TODO: Confirmar com a DGLAB
CONSTS.NIVEIS_VALIDAR_PEDIDO = [4, 6, 7]; // TODO: Confirmar com a DGLAB

// TODO: Adicionar niveis para poderem ver o histórico
